import Image from 'next/image'//importarea scripturilor pentru interactiunea imaginilor din componenta chemand clasa Image din image.js
import Head from './styled'   //importarea stilurilor din fisierul local styled.ts cu ajutorul clasei Head 


const HeadPage = () => {
  return (
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="initial-scale=1.0, width=device-width" />
      <link rel="icon" href="/favicon.ico" />
      <section className="page1">
        <div className="info1">
          <h2 id="tribute-info">Dr. Norman Borlaug</h2>
          <p id="text">The man who saved a billion lives</p>
          <p className ="years">1914 - 2009</p>
        </div>
        <div className="tribute-info">
          {/* 
            Am folosit elementul <figure> pentru a marca o fotografie într-un document 
            și un element <figcaption> pentru a defini o legendă pentru fotografie
          */}
          <figure  id="img-div"> 
            <div className="img">
              <Image id="image" src="/Images/img1.png" width={522} height={347} alt="No photo" />
            </div>
            <figcaption id="img-caption" className="fig">
              Dr. Norman Borlaug, third from the left, trains biologists in
              Mexico on how to increase wheat yields - part of his life-long war
              on hunger.
            </figcaption>
          </figure>
        </div>
        <div className="arrow">
          <p id="arrow1">&#8595;</p> 
        </div>
      </section>
    </Head>
  )
}
export default HeadPage;
