import Navbar from '../components/1.Navigation/index'
import Head from '../components/2.Head/index'
import Link from 'next/link'
import Script from 'next/script'
import Second from '../components/3.SecPage/index'
import Third from '../components/4.ThiPage/index'
import Fourth from '../components/5.ForPage/index'
import Fivth from '../components/6.FithPage/index'
import Sixth from '../components/7.SixthPage/index'
import Footer from '../components/8.Footer/index'


export default function Home (){
  return (

    <section className="id-main">
      <Navbar/>

      <Head/>
      <head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <Link href="https://www.worldfoodprize.org/en/dr_norman_e_borlaug/about_norman_borlaug/">
        <a></a>
      </Link>

      <Link href="https://bgri.cornell.edu/dr-norman-borlaug/">
        <a></a>
      </Link>

      <Second />
      <Third />
      <Fourth />
      <Fivth />
      <Sixth />

      <Footer/>

      <Script src="https://cdn.freecodecamp.org/testable-projects-fcc/v1/bundle.js"></Script>
    </section>

  );
};